name: Replace

on:
  push:
    branches:
      - action
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      base: https://dl.google.com/games/registry/unity/com.google.firebase.app/com.google.firebase.app
      version: 10.3.0
      name_version: 10_3_0
      
    steps:
    - name: Replace Content
      run: |
        rm -fr Tmp
        mkdir Tmp
        cp MetaTemplte/FirebaseCppApp-{version}.bundle.meta Tmp/FirebaseCppApp-${{ env.name_version }}.bundle.meta
        sed -i '' 's/{version}/${{ env.version }}/' Tmp/FirebaseCppApp-${{ env.name_version }}.bundle.meta
        sed -i '' 's/{name_version}/${{ env.name_version }}/' Tmp/FirebaseCppApp-${{ env.name_version }}.bundle.meta
