name: Replace

on:
  push:
    branches:
      - action
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    env:
      base: https://dl.google.com/games/registry/unity/com.google.firebase.app/com.google.firebase.app
      version: 10.7.0
      name_version: 10_7_0
    steps:
      - uses: actions/checkout@v3
      - name: Config
        run: |
          git config --local user.email "github-action@wulato.com"
          git config --local user.name "wulato-bot"
      
      - name: Replace Content
        run: |
          rm -fr Tmp
          mkdir Tmp
          cp MetaTemplate/FirebaseCppApp-{version}.bundle.meta Tmp/FirebaseCppApp-${{ env.name_version }}.bundle.meta
          echo ">>> 1"
          sed -i 's/{version}/${{ env.version }}/g' Tmp/FirebaseCppApp-${{ env.name_version }}.bundle.meta
          echo ">>> 2"
          sed -i 's/{name_version}/${{ env.name_version }}/g' Tmp/FirebaseCppApp-${{ env.name_version }}.bundle.meta
          echo ">>> 3"
      
      - name: Commit
        run: |
          git add --a
          git commit -m "Firebase SDk-v${{ env.version }}"
          git push origin
      

      
