
name: .tgz 2 Unity Package
on:
  push:
    branches:
      - ttt
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    env:
      base: https://dl.google.com/games/registry/unity/com.google.firebase.app/com.google.firebase.app
      version: 10.7.0
      so_version: 10_7_0
    steps:
      - uses: actions/checkout@v3
      - name: Config
        run: |
          git config --local user.email "github-action@wulato.com"
          git config --local user.name "wulato-bot"
      
      - name: Download Package
        run: |
          rm -rf Staging
          mkdir Staging
          cd Staging
          curl ${{ env.base }}-${{ env.version }}.tgz --output content.tgz
          tar -xvzf content.tgz
          rm content.tgz
          ls
      
      - name: Split MacOS Bundle for Desktop Support - Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-X_X_X.bundle
        run: |
          mkdir Staging/package/Firebase/Plugins/arm64
          lipo -remove x86_64 Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-${{ env.so_version }}.bundle -o Staging/package/Firebase/Plugins/arm64/FirebaseCppApp-${{ env.so_version }}.bundle
          lipo -remove arm64 Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-${{ env.so_version }}.bundle -o Staging/package/Firebase/Plugins/x86_64/FirebaseCppApp-${{ env.so_version }}.bundle
      - name: Commit
        run: |
          git add --a
          git commit -m "Package Update ${{ env.version }}"
          git push origin
     
