
name: .tgz 2 Unity Package
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    env:
      base: https://dl.google.com/games/registry/unity/com.google.firebase.app/com.google.firebase.app
      version: 10.7.0
    steps:
      - uses: actions/checkout@v3
      - name: Config
        run: |
          git config --local user.email "tianmaodi@gmail.com"
          git config --local user.name "Tian"
      
      - name: Download Package
        run: |
          rm -rf Staging
          mkdir Staging
          cd Staging
          curl ${{ env.base }}-${{ env.version }}.tgz --output content.tgz
          tar -xvzf content.tgz
          rm content.tgz
          ls
          
      - name: Commit
        run: |
          git add --a
          git commit -m "Firebase SDK v${{ env.version }}"
          git push origin
